addSbtPlugin("ch.epfl.scala"         % "sbt-scalafix"        % "0.11.1")
addSbtPlugin("com.codecommit"        % "sbt-github-actions"  % "0.14.2")
addSbtPlugin("com.github.sbt"        % "sbt-ci-release"      % "1.5.12")
addSbtPlugin("com.github.sbt"        % "sbt-native-packager" % "1.9.16")
addSbtPlugin("com.lightbend.paradox" % "sbt-paradox"         % "0.10.5")
addSbtPlugin("de.heikoseeberger"     % "sbt-header"          % "5.10.0")
addSbtPlugin("org.scalameta"         % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("org.scoverage"         % "sbt-scoverage"       % "2.0.8")
