addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"        % "0.9.34")
addSbtPlugin("com.codecommit"    % "sbt-github-actions"  % "0.14.2")
addSbtPlugin("com.github.sbt"    % "sbt-ci-release"      % "1.5.10")
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.9.7")
addSbtPlugin("com.typesafe.sbt"  % "sbt-site"            % "1.4.1")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.6.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "1.9.2")
