addSbtPlugin("ch.epfl.scala"         % "sbt-scalafix"        % "0.14.3")
addSbtPlugin("com.github.sbt"        % "sbt-github-actions"  % "0.25.0")
addSbtPlugin("com.github.sbt"        % "sbt-ci-release"      % "1.9.3")
addSbtPlugin("com.github.sbt"        % "sbt-native-packager" % "1.11.1")
addSbtPlugin("com.lightbend.paradox" % "sbt-paradox"         % "0.10.7")
addSbtPlugin("de.heikoseeberger"     % "sbt-header"          % "5.10.0")
addSbtPlugin("org.scalameta"         % "sbt-scalafmt"        % "2.5.5")
addSbtPlugin("org.scoverage"         % "sbt-scoverage"       % "2.3.1")
